version: '3'

services:
  assassin:
    build: .
    ports:
      - 8000:8000
    links:
      - mariadb
      - chromedp
    volumes:
      - ./web/:/web/
      - ./dict/:/dict/
    environment:
      - DB_Db=ag
      - DB_User=ag
      - DB_Passwd=password
      - SecretKey=biubiubiu

  mariadb:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=assassingo
      - MYSQL_DATABASE=ag
      - MYSQL_USER=ag
      - MYSQL_PASSWORD=password
      
  chromedp:
    image: knqz/chrome-headless
    ports:
      - 9222:9222
  